### ISSUE TITLE
AWS credentials?

### ISSUE THREAD

**Issue by mroswell** [nprapps/books15#103]
I'm guessing that the ugly error below is because I haven't set my AWS credentials. I have generated an Access Key ID, and a Secret Key ID for AWS. How do I incorporate them into books15?

```
(books15)marjorie (master *) books15 $ fab update
Ignoring: www/assets/assetsignore
ERROR:boto:Caught exception reading instance data
Traceback (most recent call last):
  File "/Users/marjorie/.virtualenvs/books15/lib/python2.7/site-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/Users/marjorie/anaconda/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/Users/marjorie/anaconda/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/Users/marjorie/anaconda/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/Users/marjorie/anaconda/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/Users/marjorie/anaconda/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
ERROR:boto:Unable to read instance data, giving up
Traceback (most recent call last):
  File "/Users/marjorie/.virtualenvs/books15/lib/python2.7/site-packages/fabric/main.py", line 717, in main
    *args, **kwargs
  File "/Users/marjorie/.virtualenvs/books15/lib/python2.7/site-packages/fabric/tasks.py", line 332, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/marjorie/.virtualenvs/books15/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/marjorie/WebstormProjects/books15/fabfile/__init__.py", line 136, in update
    assets.sync()
  File "/Users/marjorie/.virtualenvs/books15/lib/python2.7/site-packages/fabric/tasks.py", line 109, in __call__
    return self.run(*args, **kwargs)
  File "/Users/marjorie/.virtualenvs/books15/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/marjorie/WebstormProjects/books15/fabfile/assets.py", line 60, in sync
    bucket = utils.get_bucket(app_config.ASSETS_S3_BUCKET)
  File "/Users/marjorie/WebstormProjects/books15/fabfile/utils.py", line 28, in get_bucket
    s3 = boto.connect_s3(calling_format=OrdinaryCallingFormat())
  File "/Users/marjorie/.virtualenvs/books15/lib/python2.7/site-packages/boto/__init__.py", line 141, in connect_s3
    return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
  File "/Users/marjorie/.virtualenvs/books15/lib/python2.7/site-packages/boto/s3/connection.py", line 190, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "/Users/marjorie/.virtualenvs/books15/lib/python2.7/site-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/Users/marjorie/.virtualenvs/books15/lib/python2.7/site-packages/boto/auth.py", line 975, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials
```
```

**Comment by eads** [comment]
We will add this to our developer's guide. But in all events, you need to set the AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY environment variables.
