### ISSUE TITLE
UnicodeEncodeError: 'ascii' After lunch `fab update`

### ISSUE THREAD

**Issue by cbertelegni** [nprapps/books15#107]
After clone the repo and lunch `$ fab update`

```
$ fab update
Traceback (most recent call last):
  File "/home/cbertelegni/projects/book15pjt/ven/local/lib/python2.7/site-packages/fabric/main.py", line 717, in main
    *args, **kwargs
  File "/home/cbertelegni/projects/book15pjt/ven/local/lib/python2.7/site-packages/fabric/tasks.py", line 332, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/cbertelegni/projects/book15pjt/ven/local/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
  File "/home/cbertelegni/projects/book15pjt/books15/fabfile/__init__.py", line 135, in update
    text.update()
  File "/home/cbertelegni/projects/book15pjt/ven/local/lib/python2.7/site-packages/fabric/tasks.py", line 109, in __call__
    return self.run(*args, **kwargs)
  File "/home/cbertelegni/projects/book15pjt/ven/local/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
  File "/home/cbertelegni/projects/book15pjt/books15/fabfile/text.py", line 29, in update
    get_document(app_config.COPY_GOOGLE_DOC_KEY, app_config.COPY_PATH)
  File "/home/cbertelegni/projects/book15pjt/books15/oauth.py", line 108, in get_document
    response = app_config.authomatic.access(credentials, url)
  File "/home/cbertelegni/projects/book15pjt/ven/local/lib/python2.7/site-packages/authomatic/core.py", line 1412, in access
    content_parser=content_parser)
  File "/home/cbertelegni/projects/book15pjt/ven/local/lib/python2.7/site-packages/authomatic/providers/__init__.py", line 752, in access
    self._log(logging.INFO, 'Got response. HTTP status = {0}. {1}'.format(response.status, response.content))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 124: ordinal not in range(128)

```

**Comment by jjelosua** [comment]
Looks related to an old version of authomatic. We should update requirements.txt
