### ISSUE TITLE
error on the fab update step

### ISSUE THREAD

**Issue by mroswell** [nprapps/books15#99]
My guess-- and I'm not sure yet--is that I need to  create the spreadsheet described in 'COPY editing' section, before 'fab update' will work.

Will let you know if that is the case.

```
IOError
IOError: [Errno 2] No such file or directory: 'www/static-data/books.json'

Traceback (most recent call last)
File "/Users/marjorieroswell/.virtualenvs/books15/lib/python2.7/site-packages/flask/app.py", line 1701, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/marjorieroswell/.virtualenvs/books15/lib/python2.7/site-packages/flask/app.py", line 1689, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/Users/marjorieroswell/.virtualenvs/books15/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
response = self.full_dispatch_request()
File "/Users/marjorieroswell/.virtualenvs/books15/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/marjorieroswell/.virtualenvs/books15/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/marjorieroswell/.virtualenvs/books15/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/marjorieroswell/WebstormProjects/books15/oauth.py", line 71, in decorated_function
return f(*args, **kwargs)
File "/Users/marjorieroswell/WebstormProjects/books15/app.py", line 41, in index
with open('www/static-data/books.json', 'rb') as readfile:
IOError: [Errno 2] No such file or directory: 'www/static-data/books.json'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it.

Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

**Comment by eads** [comment]
This is our bad -- we need to provide spreadsheet access. I'll work on that.

**Comment by mroswell** [comment]
Not sure if this belongs in a new issue, but maybe will be helpful here.

I manually replicated the linked spreadsheet:
https://docs.google.com/spreadsheets/d/1pogl4JaaIkEcXvPu2zDbTo_I4uLNSEm0vB8WxnNPBuU/pub#

Then added worksheets: 
- tags
- attribution

and keys:
- content.header_subhead
- content.header_title
- content.clear_filters
- content.chatter
- attribution.byline

**Comment by mroswell** [comment]
It took a bit for me to notice that a second spreadsheet is needed, with a header row for these keys:

- title
- genre
- author
- isbn
- book_seamus_id
- hide_ibooks
- text
- reviewer
- slug
- tags
- reviewer ID
- reviewer link
- html text
- oclc
